### ISSUE TITLE
Time seems to be in summer time or wrong time zone

### ISSUE THREAD

**Issue by bennet21** [bramvanduinen/IMAU-counter#2]
The updated time stamp is one hour ahead of Utrecht time

**Comment by bramvanduinen** [comment]
Yes, this is a known issue. I don't know what causes it yet, because it seems to be working fine when I run the app locally. I will look into it later today.

**Comment by bramvanduinen** [comment]
I just solved this, so I will close the issue now. Thanks for mentioning it.
